In [38]:
%pip install pandas lxml --upgrade

Requirement already satisfied: pandas in c:\users\giatu\appdata\local\programs\python\python312\lib\site-packages (3.0.6)
Requirement already satisfied: lxml in c:\users\giatu\appdata\local\programs\python\python312\lib\site-packages (6.1.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\giatu\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.5.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\giatu\appdata\roaming\python\python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\giatu\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2026.5)
Requirement already satisfied: six>=1.5 in c:\users\giatu\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [39]:
## Original method from the book
import pandas as pd
URL = "https://en.wikipedia.org/wiki/List_of_world_records_in_swimming"

In [40]:
# Failed with HTTP 403: Forbidden
#tables = pd.read_html(URL)

In [41]:
#AI code to fix HTTP Error 403: Forbidden,a workaround for the error with using gazpacho to change User-agent identity to a normal web brower
import pandas as pd
import gazpacho
from io import StringIO

URL = "https://en.wikipedia.org/wiki/List_of_world_records_in_swimming"

html = gazpacho.get(URL)
tables = pd.read_html(StringIO(html))

len(tables)

24

In [42]:
# Alternative: Pandas with a custom User-Agent name

# headers = {
#     "User-Agent": "MySwimmingRecordsLearningProject/1.0"
# }

# tables = pd.read_html(URL, storage_options=headers)

In [43]:
tables[0].head()

,Event,Time,Unnamed: 2,Name,Nationality,Date,Meet,Location,Ref
0,50m freestyle,20.88,NaN,Cameron McEvoy,Australia,20 March 2026,China Open,"Shenzhen, China",[10]
1,100m freestyle,46.40,NaN,Pan Zhanle,China,31 July 2024,Olympic Games,"Paris, France",[11]
2,200m freestyle,1:42.00,ss,Paul Biedermann,Germany,28 July 2009,World Championships,"Rome, Italy",[12][13][14]
3,400m freestyle,3:39.96,NaN,Lukas Märtens,Germany,12 April 2025,Swim Open Stockholm,"Stockholm, Sweden",[15]
4,800m freestyle,7:32.12,ss,Zhang Lin,China,29 July 2009,World Championships,"Rome, Italy",[16][17]

In [44]:
df = tables[0][["Event", "Time"]] #Inner [] creates a list of 2 column names. Outer [] tells Pandas to select those columns.

In [45]:
df.head()

            Event     Time
0   50m freestyle    20.88
1  100m freestyle    46.40
2  200m freestyle  1:42.00
3  400m freestyle  3:39.96
4  800m freestyle  7:32.12

In [46]:
df.to_dict()

{'Event': {0: '50m freestyle',
  1: '100m freestyle',
  2: '200m freestyle',
  3: '400m freestyle',
  4: '800m freestyle',
  5: '1500m freestyle',
  6: '50m backstroke',
  7: '100m backstroke',
  8: '200m backstroke',
  9: '50m breaststroke',
  10: '100m breaststroke',
  11: '200m breaststroke',
  12: '200m breaststroke',
  13: '50m butterfly',
  14: '100m butterfly',
  15: '200m butterfly',
  16: '200m individual medley',
  17: '400m individual medley',
  18: '4 × 100 m freestyle relay',
  19: '4 × 200 m freestyle relay',
  20: '4 × 100 m medley relay'},
 'Time': {0: '20.88',
  1: '46.40',
  2: '1:42.00',
  3: '3:39.96',
  4: '7:32.12',
  5: '14:26.79',
  6: '23.55',
  7: '51.60',
  8: '1:51.92',
  9: '25.95',
  10: '56.88',
  11: '2:05.48',
  12: '2:04.83',
  13: '22.27',
  14: '49.45',
  15: '1:50.34',
  16: '1:52.69',
  17: '4:02.50',
  18: '3:08.24',
  19: '6:58.55',
  20: '3:26.78'}}

In [47]:
df.tail()

                        Event     Time
16     200m individual medley  1:52.69
17     400m individual medley  4:02.50
18  4 × 100 m freestyle relay  3:08.24
19  4 × 200 m freestyle relay  6:58.55
20     4 × 100 m medley relay  3:26.78

In [48]:
df[df["Event"].str.contains("relay")]

                        Event     Time
18  4 × 100 m freestyle relay  3:08.24
19  4 × 200 m freestyle relay  6:58.55
20     4 × 100 m medley relay  3:26.78

In [49]:
df[~df["Event"].str.contains("relay")] # ~ flip the meaning of the conditional 
                                       # put character immediately before the conditonal which excludes relay records

                     Event      Time
0            50m freestyle     20.88
1           100m freestyle     46.40
2           200m freestyle   1:42.00
3           400m freestyle   3:39.96
4           800m freestyle   7:32.12
5          1500m freestyle  14:26.79
6           50m backstroke     23.55
7          100m backstroke     51.60
8          200m backstroke   1:51.92
9         50m breaststroke     25.95
10       100m breaststroke     56.88
11       200m breaststroke   2:05.48
12       200m breaststroke   2:04.83
13           50m butterfly     22.27
14          100m butterfly     49.45
15          200m butterfly   1:50.34
16  200m individual medley   1:52.69
17  400m individual medley   4:02.50

In [50]:
df = df[~df["Event"].str.contains("relay")] #overwrite the existing dataframe (in df) with this filtered data

In [51]:
df = df.set_index("Event") #set the index to the Event column
df.head()

                   Time
Event
50m freestyle     20.88
100m freestyle    46.40
200m freestyle  1:42.00
400m freestyle  3:39.96
800m freestyle  7:32.12

In [52]:
df.to_dict()

{'Time': {'50m freestyle': '20.88',
  '100m freestyle': '46.40',
  '200m freestyle': '1:42.00',
  '400m freestyle': '3:39.96',
  '800m freestyle': '7:32.12',
  '1500m freestyle': '14:26.79',
  '50m backstroke': '23.55',
  '100m backstroke': '51.60',
  '200m backstroke': '1:51.92',
  '50m breaststroke': '25.95',
  '100m breaststroke': '56.88',
  '200m breaststroke': '2:04.83',
  '50m butterfly': '22.27',
  '100m butterfly': '49.45',
  '200m butterfly': '1:50.34',
  '200m individual medley': '1:52.69',
  '400m individual medley': '4:02.50'}}

In [53]:
records = {}
records["LC Men"] = df.to_dict()["Time"] #get the dictionary of times from the dataframe and assign it to the records dictionary under the key "LC Men"

In [54]:
records

{'LC Men': {'50m freestyle': '20.88',
  '100m freestyle': '46.40',
  '200m freestyle': '1:42.00',
  '400m freestyle': '3:39.96',
  '800m freestyle': '7:32.12',
  '1500m freestyle': '14:26.79',
  '50m backstroke': '23.55',
  '100m backstroke': '51.60',
  '200m backstroke': '1:51.92',
  '50m breaststroke': '25.95',
  '100m breaststroke': '56.88',
  '200m breaststroke': '2:04.83',
  '50m butterfly': '22.27',
  '100m butterfly': '49.45',
  '200m butterfly': '1:50.34',
  '200m individual medley': '1:52.69',
  '400m individual medley': '4:02.50'}}

In [56]:
RECORDS = (0, 1, 3, 4)
COURSES = ("LC Men", "LC Women", "SC Men", "SC Women")

records = {}
for table, course in zip(RECORDS, COURSES):
    df = tables[table][["Event", "Time"]] #Inner [] creates a list of 2 column names. Outer [] tells Pandas to select those columns.
    df = df[~df["Event"].str.contains("relay")] #exclude relay records
    df = df.set_index("Event") #set the index to the Event column
    records[course] = df.to_dict()["Time"] #get the dictionary of times from the dataframe and assign it to the records dictionary under the key "course"

In [67]:
import json

with open("records.json") as jf:
    gazpacho_records = json.load(jf)

records == gazpacho_records

True

In [68]:
for course in records:
    print(course, records[course] == gazpacho_records[course])

LC Men True
LC Women True
SC Men True
SC Women True

In [71]:
records["SC Women"]["100m butterfly"]

'52.71'

In [72]:
gazpacho_records["SC Women"]["100m butterfly"]

'52.71'